### ISSUE TITLE
RS485 modbus

### ISSUE THREAD

**Issue by dzurikmiroslav** [monarco/node-red-contrib-monarco-hat#2]
Hello, 
I have flow to read register values from modbus device periodically, trough node-red-contrib-modbus.

Randomly gave me error: [error] [modbus-getter:2100H] Timed out

RS485 and UART config parameter seems OK.
On RPI4 I was try to disable bluetooth service, but not help.

Please can you help me? Thanks in advance

**Comment by rajtik** [comment]
Hello,
how often does the error occur? Is it in seconds, minutes or hours? Did you manage to read/write any data? Take a look at this manual :) [https://support.monarco.io/help/rs-485-on-the-monarco-hat](https://support.monarco.io/help/rs-485-on-the-monarco-hat).

Cheers,
Jan

**Comment by dzurikmiroslav** [comment]
I am sorry, the problem was probably caused by poor cable quality.
Solved reduction of baud rate...
